---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: debug-nodepool
spec:
  template:
    metadata:
      labels:
        nodegroup: debug
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values: ["4"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: debug-class
      expireAfter: 720h
      taints:
        - key: debug-only
          value: "true"
          effect: NoSchedule
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 15m
    budgets:
    - nodes: 10%
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: debug-class
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - alias: al2023@v20251120
  role: Karpenter-eks-platform-us-east-1-20250311134036805600000006
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery/eks-platform-us-east-1: "eks-platform-us-east-1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery/eks-platform-us-east-1: "eks-platform-us-east-1"
