---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-test-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-test
  template:
    metadata:
      labels:
        app: debug-test
    spec:
      # Tolerate the debug-only taint
      tolerations:
        - key: debug-only
          operator: Equal
          value: "true"
          effect: NoSchedule
      # Request scheduling on debug nodepool
      nodeSelector:
        nodegroup: debug
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
      restartPolicy: Always
